name: Test
on:
  pull_request:
    branches: [main, dev]

permissions:
  id-token: write
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      DATABASE_URL: postgres://postgres:postgres@localhost:5432/grimity
      JWT_SECRET: test
      JWT_EXPIRES_IN: 1d
      JWT_REFRESH_SECRET: test
      JWT_REFRESH_EXPIRES_IN: 7d
      AWS_IMAGE_BUCKET_NAME: grimity-image-dev
      AWS_REGION: ap-northeast-2
      REDIS_HOST: localhost
      IMAGE_URL: http://image.localhost
      FIREBASE_ADMIN_SDK_PROJECT_ID: ${{ secrets.DEV_FIREBASE_ADMIN_SDK_PROJECT_ID }}
      FIREBASE_ADMIN_SDK_CLIENT_EMAIL: ${{ secrets.DEV_FIREBASE_ADMIN_SDK_CLIENT_EMAIL }}
      FIREBASE_ADMIN_SDK_PRIVATE_KEY: ${{ secrets.DEV_FIREBASE_ADMIN_SDK_PRIVATE_KEY }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          role-session-name: github-actions
          aws-region: ap-northeast-2

      - name: Start PostgreSQL
        run: docker run --name postgres -e POSTGRES_PASSWORD=postgres -d -p 5432:5432 postgres:16

      - name: Start Redis
        run: docker run --name redis -d -p 6379:6379 redis

      - name: Install dependencies
        run: |
          npm ci
          npx prisma db push

      - name: Run E2E tests
        run: |
          npm run test:e2e

      - name: Run Unit tests
        run: |
          npm run test:unit
